name: Acceptance
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run docker-compose stack
      run: docker-compose -f docker-compose.ci.yml up -d
    - name: List containers
      run: docker ps
    - name: Wait for containers
      run: sleep 180
    - name: List containers 2
      run: docker ps
    - name: List containers 2
      run: docker-compose -f docker-compose.ci.yml logs ui
    - name: Run acceptance tests
      run: docker-compose -f docker-compose.ci.yml -T exec ui npm run acceptance:fr